version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - checkout
      - run:
           name: Show circle branch
           command: echo ${CIRCLE_BRANCH}
      - restore_cache:
           keys:
             - app-{{ checksum "package.json" }}
             - app
      - run:
          name: Install yarn
          command: npm install -g yarn 
      - run:
          name: Intsall dependecies
          command: npm Install
         
      - save_cache:
          paths:
            - node_modules
          key:
            - app-{{ checksum "package.json" }}

deploy-to-aws-s3:
  docker:
    - image: circleci/node:latest
  working_directory: ~/project
  steps:
    - checkout
    - run:
        name: Show circle branch
        command: echo ${CIRCLE_BRANCH}
    - run:
        name: Installing AWS CLI
        working_directory: ~/ 
        command: |
          sudo apt-get -t -qq update
          suod apt-get install -y awscli 
          sudo apt-get install -y python-pip python-dev build-essential 
           
    - run:
        name: build Project
        command: |
          npm install
          npm run build
          cd build 
          zip ../build.zip -r * .[^.]*
          echo "Build successfull"
    - run:
        name: Deploy to AWS S3
        command: |
          if [ "${CIRCLE_BRANCH}" == "main" ] 
          then
            aws --region ${AWS_REGION} s3 sync ~/project/build s3://${AWS_PROD_BUCKET} --delete
          elif [ "${CIRCLE_BRANCH}" == "stage"]
            aws --region ${AWS_REGION} s3 sync ~/project/build s3://${AWS_STAGE_BUCKET} --delete
          else
            aws --region ${AWS_REGION} s3 sync ~/project/build s3://${AWS_DEV_BUCKET} --delete 
          fi


deploy-to-aws-cloudfront:
  docker:
    - image: circleci/node:latest
  working_directory: ~/project
  steps:
    - checkout
    - run:
        name: Show circle branch
        command: echo ${CIRCLE_BRANCH}
    - run:
        name: Installing AWS CLI
        working_directory: ~/ 
        command: |
          sudo apt-get -t -qq update
          suod apt-get install -y awscli 
          sudo apt-get install -y python-pip python-dev build-essential 
           
    - run:
        name: build Project
        command: |
          npm install
          npm run build
          cd build 
          zip ../build.zip -r * .[^.]*
          echo "Build successfull"
    - run:
        name: Deploy to AWS Cloudfront
        command: |
          aws configure set preview.cloudfront true
          if [ "${CIRCLE_BRANCH}" == "main" ]
          then
            aws cloudfront create-invalidation --disturbation-id ${PROD_DISTRIBUTION_ID} --paths /\*
          elif [ "${CIRCLE_BRANCH}" == "stage"]
            aws cloudfront create-invalidation --disturbation-id ${STAGE_DISTRIBUTION_ID} --paths /\* 
          else
            aws cloudfront create-invalidation --disturbation-id ${DEV_DISTRIBUTION_ID} --paths /\* 
          fi


workflow:
  build_and_deploy:
    jobs:
      - build
      - deploy-to-aws-s3:
          reques:
            - build
          filters:
            branches:
              only:
                - develope
                - stage 
                - main
      - deploy-to-aws-cloudfront:
          reques:
            - deploy-to-aws-s3
          filters:
            branches:
              only:
                - develope
                - stage 
                - main
